export const STREET_ABBREVIATIONS: Record<string, string> = {
  avenue: 'ave',
  boulevard: 'blvd',
  circle: 'cir',
  court: 'ct',
  drive: 'dr',
  expressway: 'expy',
  highway: 'hwy',
  lane: 'ln',
  parkway: 'pkwy',
  place: 'pl',
  road: 'rd',
  square: 'sq',
  street: 'st',
  terrace: 'ter',
  trail: 'trl',
  way: 'way',
  suite: 'ste',
  apartment: 'apt',
  building: 'bldg',
  department: 'dept',
  floor: 'fl',
  room: 'rm',
  north: 'n',
  south: 's',
  east: 'e',
  west: 'w',
  northeast: 'ne',
  northwest: 'nw',
  southeast: 'se',
  southwest: 'sw',
};

export const COUNTRY_NAMES_TO_ISO: Record<string, string> = {
  'united states': 'US',
  'united states of america': 'US',
  usa: 'US',
  india: 'IN',
  bharat: 'IN',
  'united kingdom': 'GB',
  uk: 'GB',
  great_britain: 'GB',
  canada: 'CA',
  germany: 'DE',
  deutschland: 'DE',
  france: 'FR',
  australia: 'AU',
  qatar: 'QA',
  'united arab emirates': 'AE',
  uae: 'AE',
  singapore: 'SG',
  japan: 'JP',
};
